### ISSUE TITLE
Threading not working if emcee is installed

### ISSUE THREAD

**Issue by Zstone19** [nye17/javelin#11]
Firstly, thank you for the continued updates to javelin. I've noticed that when trying to run javelin on multiple cores, it only runs on one no matter what I feed the ``threads`` argument in ``do_mcmc``. Digging into it a bit more, I found that lcmodel.py will use the ``EnsembleSampler`` object from emcee if it is already installed instead of the object from the internal sampler. However, the ``do_mcmc`` function will pass the ``threads`` argument to emcee's ``EnsembleSampler``, which is deprecated and no longer works. The threading does work after uninstalling emcee, using the internal sampler. 

I could be missing something here, so any help would be greatly appreciated. Thanks!

**Comment by nye17** [comment]
Thanks! I've changed the default behavior to be using the internal emcee rather than the system-wide one, because there is no way that the cadence of javelin updates can catch up with that of emcee!
