### ISSUE TITLE
installation in MacBookPro with M1 chips

### ISSUE THREAD

**Issue by brettlv** [nye17/javelin#8]
MacBookPro with M1 chips

ImportError: dlopen(/Users/lyubing/opt/anaconda3/lib/python3.9/site-packages/javelin/gp/linalg_utils.cpython-39-darwin.so, 0x0002): tried: '/Users/lyubing/opt/anaconda3/lib/python3.9/site-packages/javelin/gp/linalg_utils.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))

**Comment by nye17** [comment]
This is a hard one to crack, given that I don't have a Mac with M1 chip to play with. However, it does seem like a generic compatibility issue of M1 with fortran libraries, maybe the issue is well documented somewhere else among the fortran users?

**Comment by nye17** [comment]
The current version works on my new MacBookPro with M2 chips.
